# Generated by Django 4.2.4 on 2024-11-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_alter_product_fin_prdt_cd'),
        ('accounts', '0002_user_earn_user_family_user_know_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='finlife.product'),
        ),
    ]
