# Generated by Django 4.2.16 on 2024-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_cd',
            field=models.CharField(max_length=255),
        ),
    ]
